stages:
  prepare:
    cmd: python src/graph.py data/followers.csv
    deps:
    - data/followers.csv
    - src/graph.py
    outs:
    - data/output
  nodes:
    cmd: python src/nodes.py
    deps:
    - data/output/graph.json
    - src/nodes.py
    outs:
    - data/nodes
  count:
    cmd: python src/count.py
    deps:
    - data/nodes/nodes.json
    - src/count.py
    outs:
    - data/count
